# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import two_phase_commit_pb2 as two__phase__commit__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in two_phase_commit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub(object):
    """Coordinator service (for client requests)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTransaction = channel.unary_unary(
                '/twopc.CoordinatorService/ExecuteTransaction',
                request_serializer=two__phase__commit__pb2.TransactionRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.GetBalances = channel.unary_unary(
                '/twopc.CoordinatorService/GetBalances',
                request_serializer=two__phase__commit__pb2.BalanceRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.SetScenario = channel.unary_unary(
                '/twopc.CoordinatorService/SetScenario',
                request_serializer=two__phase__commit__pb2.ScenarioRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.ScenarioResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """Coordinator service (for client requests)
    """

    def ExecuteTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTransaction,
                    request_deserializer=two__phase__commit__pb2.TransactionRequest.FromString,
                    response_serializer=two__phase__commit__pb2.TransactionResponse.SerializeToString,
            ),
            'GetBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalances,
                    request_deserializer=two__phase__commit__pb2.BalanceRequest.FromString,
                    response_serializer=two__phase__commit__pb2.BalanceResponse.SerializeToString,
            ),
            'SetScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.SetScenario,
                    request_deserializer=two__phase__commit__pb2.ScenarioRequest.FromString,
                    response_serializer=two__phase__commit__pb2.ScenarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """Coordinator service (for client requests)
    """

    @staticmethod
    def ExecuteTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.CoordinatorService/ExecuteTransaction',
            two__phase__commit__pb2.TransactionRequest.SerializeToString,
            two__phase__commit__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.CoordinatorService/GetBalances',
            two__phase__commit__pb2.BalanceRequest.SerializeToString,
            two__phase__commit__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.CoordinatorService/SetScenario',
            two__phase__commit__pb2.ScenarioRequest.SerializeToString,
            two__phase__commit__pb2.ScenarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ParticipantServiceStub(object):
    """Participant service (for 2PC from coordinator)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prepare = channel.unary_unary(
                '/twopc.ParticipantService/Prepare',
                request_serializer=two__phase__commit__pb2.PrepareRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/twopc.ParticipantService/Commit',
                request_serializer=two__phase__commit__pb2.CommitRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/twopc.ParticipantService/GetBalance',
                request_serializer=two__phase__commit__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.SetBalance = channel.unary_unary(
                '/twopc.ParticipantService/SetBalance',
                request_serializer=two__phase__commit__pb2.SetBalanceRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.SetBalanceResponse.FromString,
                _registered_method=True)
        self.SetCrashMode = channel.unary_unary(
                '/twopc.ParticipantService/SetCrashMode',
                request_serializer=two__phase__commit__pb2.CrashModeRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.CrashModeResponse.FromString,
                _registered_method=True)


class ParticipantServiceServicer(object):
    """Participant service (for 2PC from coordinator)
    """

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCrashMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParticipantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=two__phase__commit__pb2.PrepareRequest.FromString,
                    response_serializer=two__phase__commit__pb2.PrepareResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=two__phase__commit__pb2.CommitRequest.FromString,
                    response_serializer=two__phase__commit__pb2.CommitResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=two__phase__commit__pb2.GetBalanceRequest.FromString,
                    response_serializer=two__phase__commit__pb2.GetBalanceResponse.SerializeToString,
            ),
            'SetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBalance,
                    request_deserializer=two__phase__commit__pb2.SetBalanceRequest.FromString,
                    response_serializer=two__phase__commit__pb2.SetBalanceResponse.SerializeToString,
            ),
            'SetCrashMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCrashMode,
                    request_deserializer=two__phase__commit__pb2.CrashModeRequest.FromString,
                    response_serializer=two__phase__commit__pb2.CrashModeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.ParticipantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.ParticipantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParticipantService(object):
    """Participant service (for 2PC from coordinator)
    """

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.ParticipantService/Prepare',
            two__phase__commit__pb2.PrepareRequest.SerializeToString,
            two__phase__commit__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.ParticipantService/Commit',
            two__phase__commit__pb2.CommitRequest.SerializeToString,
            two__phase__commit__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.ParticipantService/GetBalance',
            two__phase__commit__pb2.GetBalanceRequest.SerializeToString,
            two__phase__commit__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.ParticipantService/SetBalance',
            two__phase__commit__pb2.SetBalanceRequest.SerializeToString,
            two__phase__commit__pb2.SetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCrashMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.ParticipantService/SetCrashMode',
            two__phase__commit__pb2.CrashModeRequest.SerializeToString,
            two__phase__commit__pb2.CrashModeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RaftServiceStub(object):
    """Raft service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendEntries = channel.unary_unary(
                '/twopc.RaftService/AppendEntries',
                request_serializer=two__phase__commit__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)
        self.RequestVote = channel.unary_unary(
                '/twopc.RaftService/RequestVote',
                request_serializer=two__phase__commit__pb2.RequestVoteRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.RequestVoteResponse.FromString,
                _registered_method=True)


class RaftServiceServicer(object):
    """Raft service
    """

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=two__phase__commit__pb2.AppendEntriesRequest.FromString,
                    response_serializer=two__phase__commit__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=two__phase__commit__pb2.RequestVoteRequest.FromString,
                    response_serializer=two__phase__commit__pb2.RequestVoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.RaftService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.RaftService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RaftService(object):
    """Raft service
    """

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.RaftService/AppendEntries',
            two__phase__commit__pb2.AppendEntriesRequest.SerializeToString,
            two__phase__commit__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.RaftService/RequestVote',
            two__phase__commit__pb2.RequestVoteRequest.SerializeToString,
            two__phase__commit__pb2.RequestVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
